import 'server-only'

import { createHash, randomBytes } from 'node:crypto'

/**
 * PKCE, in one place.
 *
 * X and TikTok both require it; Meta and LinkedIn do not. Written here rather
 * than in each adapter so there is one implementation to get right — the
 * failure mode of a wrong challenge is an opaque `invalid_grant` at the token
 * endpoint, which is miserable to debug four times over.
 *
 * The verifier is generated by the route and stored in the encrypted state
 * cookie; only its S256 hash travels to the provider. That is the whole point:
 * an intercepted authorization code is useless without the verifier, which
 * never left this server.
 */

/** 43–128 characters of unreserved ASCII, per RFC 7636. 32 bytes gives 43. */
export function createVerifier(): string {
  return randomBytes(32).toString('base64url')
}

export function challengeFor(verifier: string): string {
  return createHash('sha256').update(verifier).digest('base64url')
}

export const CHALLENGE_METHOD = 'S256'
